version: '3.9'
services:
  frontend:
    container_name: frontend
    image: frontend
    build:
          context: ./frontend
          dockerfile: Dockerfile
    ports:
      - '5173:5173'
    env_file:
      - ./frontend/.env
  nestapp:
    container_name: nestapp
    image: francescoxx/nestapp:1.0.0
    build:
          context: ./backend
          dockerfile: Dockerfile
    ports:
      - '3000:3000'
      - '3131:3131'
    env_file:
      - ./backend/.env
    depends_on:
      - db
  db:
    container_name: db
    image: postgres
    pull_policy: never
    build: ./backend/postgres
    env_file:
      - ./backend/.env
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: {}
